name: Data Preprocessing Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'rawdata/heart.csv'
      - 'preprocessing/automate_Deaka.py'
      - '.github/workflows/preprocess-data.yml'
  workflow_dispatch:

jobs:
  preprocess-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Run preprocessing
      shell: bash
      run: |
        echo "Running automate_Deaka.py with args:"
        echo "--input_path rawdata/heart.csv --output_path preprocessing/heart_preprocessed.csv"
        python preprocessing/automate_Deaka.py \
          --input_path rawdata/heart.csv \
          --output_path preprocessing/heart_preprocessed.csv

    - name: Upload processed data
      uses: actions/upload-artifact@v4
      with:
        name: processed-data
        path: preprocessing/heart_preprocessed.csv
